### ISSUE TITLE
add_monochrome

### ISSUE THREAD

**Issue by fluidpixel** [Rolf-Hempel/PlanetarySystemStacker#1]
`add_monochrome` isn't in frames.py, yet is still referenced throughout the codebase, particularly from main_program.py. Copying from frames_old.py solves the error, but it appears `add_monochrome` is being deprecated?

**Comment by Rolf-Hempel** [comment]
You are right: I removed "add_monochrome" recently when I implemented partial buffering. It should not be copied from "frames_old.py" becuase it is obsolete. I just deleted references to it throughout the whole code base. Thanks for reminding me!

Actually, "main_program.py" is only for test purposes. It runs the workflow in single-threaded mode without a GUI. The "real" program start is to call "planetary_system_stacker.py".
