### ISSUE TITLE
Wrong year 2019 for v0.7.0 in UserGuide

### ISSUE THREAD

**Issue by rovnanik** [Rolf-Hempel/PlanetarySystemStacker#20]
Hi,
there is a wrong year 2019 for 0.7.0 release in PlanetarySystemStacker_User-Guide.

now is:
2.1 Changes in version 0.7.0 (February 2019)

should be:
2.1 Changes in version 0.7.0 (February 2020)

**Comment by Rolf-Hempel** [comment]
Hi,

I discovered that already. It will be fixed with the next release.
