### ISSUE TITLE
libmkl_rt.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rovnanik** [Rolf-Hempel/PlanetarySystemStacker#22]
Hi, on my Linux I am getting this warning:

$ python3 planetary_system_stacker.py 
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
09-28-31.7 Warning: mkl_rt.dll / libmkl_rt.so does not work (not a Windows or Linux system, or Intel Math Kernel Library not installed?). libmkl_rt.so: cannot open shared object file: No such file or directory

But the library exists:
$ locate libmkl_rt.so
/usr/local/lib/libmkl_rt.so

Solved by adding /usr/local/lib to LD_LIBRARY_PATH variable:
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

Should be mentioned in the User Guide at least.

**Comment by Rolf-Hempel** [comment]
Hi,

Thanks for this remark. I will add a note in the User Guide with the next release.

Regards,
 Rolf
