### ISSUE TITLE
Cannot lower "Protocol detail level" and "Data buffering level" using the down button

### ISSUE THREAD

**Issue by rovnanik** [Rolf-Hempel/PlanetarySystemStacker#23]
Hi, 
I cannot lower the value of "Protocol detail level" and "Data buffering level" using the down button.

I can set it higher with the up button, set it higher or lower with the arrow keys (using keyboard) and write the exact value.

![image](https://user-images.githubusercontent.com/62076614/76554855-dcc52100-6496-11ea-8806-4a7379c6e7df.png)

**Comment by Rolf-Hempel** [comment]
Hi,
Where in the User Guide did you read that the two fields can be modified using the up and down buttons?

Even though it is not a guaranteed feature, on my computers the up and down buttons work on both fields.

Regards,
 Rolf
