### ISSUE TITLE
Error processing the provided 16bit_mono.ser file

### ISSUE THREAD

**Issue by selste** [Rolf-Hempel/PlanetarySystemStacker#24]
Hi,
after cloning the repository and installing all the required Python libraries i tried processing the provided samples first.
The above mentioned 16bit_mono.ser file results in the following error message:

18-58-58.6 Start processing /[...]/PlanetarySystemStacker/Source/Videos/16bit_mono.ser

18-58-58.6 +++ Start ranking images +++
OpenCV Error: Unsupported format or combination of formats () in threshold, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/thresh.cpp, line 1431
18-59-05.0 Error: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/thresh.cpp:1431: error: (-210)  in function threshold
, continuing with next job

The 'About PSS' dialog shows the following information:
System overview:
CPU Cores: 8
Memory: 15.6 [GB]
OS: Linux 4.15.0-91-generic 64bit

Software versions used:
Python: 3.6.9
Qt: 5.9.5
Matplotlib: 2.1.1
OpenCV: 3.2.0
Numpy: 1.13.3
Psutil: 5.4.2
Scipy: 0.19.1
Scikit-image: 0.13.1
Astropy: 3.0
Pip: 9.0.1

Do You need any further information to diagnose the issue and possibly fix it?
Regards,

Steffen

**Comment by Rolf-Hempel** [comment]
Hi Steffen,

This is the same issue as was discussed [here](https://github.com/Rolf-Hempel/PlanetarySystemStacker/issues/21). In that case the user even sent me the the image files with which he got the error. On all machines I had access to, however, (using Windows 10 or Ubuntu Linux 16.04.) the error did not occur. So, as it stands now, it is impossible for me to reproduce or fix the problem. The only thing I know for sure is that it has nothing to do with my code.

The problem must be related to some incompatibility within the Python 3 installation. At first sight, however, I don't see any communality in the library versions used in the Linux installations where the error occurred.

Sorry, I don't have a clue what is the cause of this.

Best Regards,
 Rolf

**Comment by selste** [comment]
Good morning Rolf,
Thank You for the fast reply!

That's a bit unfortunate - and my bad that i failed to check the already closed issues.
I'll give it a try on another machine, worst case i'll have to wait until the 20.04 LTS is released because i intend to reinstall my desktop then anyways.
Cheers,

Steffen
