### ISSUE TITLE
Error installing on Raspberry Pi 4B

### ISSUE THREAD

**Issue by rbarbera** [Rolf-Hempel/PlanetarySystemStacker#28]
I'm having problems trying to install PSS on a Raspberry with Astroberry distro on it. When I launch the `pip3 install planetary-system-stacker` I receive this error

```
astroberry@astroberry:~ $ pip3 install planetary-system-stacker
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement planetary-system-stacker (from versions: none)
ERROR: No matching distribution found for planetary-system-stacker
```

Any idea on what could I'm doing wrong? 

```
astroberry@astroberry:~ $ python3 --version
Python 3.7.3
```

**Comment by rbarbera** [comment]
After reading a closed issue and the reference on CloudyNights about `astropy`, I've tried to upgrade my installation with no success:

```
astroberry@astroberry:~ $ pip3 install --upgrade astropy
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting astropy
  Downloading https://www.piwheels.org/simple/astropy/astropy-4.0.1.post1-cp37-cp37m-linux_armv7l.whl (10.3 MB)
     |████████████████████████████████| 10.3 MB 3.6 MB/s 
Requirement already satisfied, skipping upgrade: numpy>=1.16 in /usr/lib/python3/dist-packages (from astropy) (1.16.2)
Installing collected packages: astropy
Successfully installed astropy-4.0.1.post1
astroberry@astroberry:~ $ pip3 install planetary-system-stacker
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement planetary-system-stacker (from versions: none)
ERROR: No matching distribution found for planetary-system-stacker
```

**Comment by Rolf-Hempel** [comment]
Hi,

The error message says that there is no wheel file for the ARM processor on the PyPI server. That is correct. I regularly upload files for Windows, Linux (on Intel architecture) and MacOS on the server, as you can see in this screenshot:

![grafik](https://user-images.githubusercontent.com/19596791/93807927-9f163180-fc4b-11ea-93e0-7e0e8fe617ee.png)

I don't have a Raspberry Pi for development and testing, so I did not write the corresponding setup script. If somebody is willing to write and test such a script for the ARM architecture, he or she can send me a pull request. I could then include it in the regular upload of new versions on PyPI.

All the best,
 Rolf

**Comment by rbarbera** [comment]
Well, I've tried to use the standard Linux setup, but I don't have access to the test pip repo for planetary-system-stacker

```
astroberry@astroberry:~/PSS/PlanetarySystemStacker $ python3 -m twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: rbarberac
Enter your password: 
Uploading planetary_system_stacker-0.8.0-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████| 206k/206k [00:01<00:00, 158kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
The user 'rbarberac' isn't allowed to upload to project 'planetary-system-stacker'. See https://test.pypi.org/help/#project-name for more information.
```

**Comment by rbarbera** [comment]
After trying to install from this `.whl` file, I think that it will be not possible. At least with my naive approach: it tries to compile the full Qt subsystem and this is too much for the Raspberry and I don't know enough about this kind of builds to accelerate the process.

It's very odd, because yesterday I've build KStars/Ekos from the repo and it was vey fast.

**Comment by rbarbera** [comment]
Ok, progress report. After searching on Debian APT repositories for the raspberry I've been able to solve all the dependencies except one: `mkl`. I've read that this library is related with optimization on Intel processors. As the Raspberry doesn't have this kind of processors (it uses some ARM based chip) I don't know if this dependency apply at all.

**Comment by Rolf-Hempel** [comment]
Hi Rafa,

mkl is not used by PSS directly. Therefore, if you have installed all the other dependencies, PSS should be happy. There is one place where PSS tries to access mkl itself, but if it does not find the library this only results in a warning (performance might be reduced).

I still don't know how to create the wheel file for ARM, and I don't want to spend my time in researching that myself. For Linux I created it with "python3 setup_linux.py bdist_wheel --plat-name manylinux1_x86_64", but that obviously only matches Intel processor-based systems. I want to avoid using a platform description which on Intel-based machines could be confused with the more appropriate one.

I also wonder if installing PSS on a Raspberry Pi would make sense at all. The processor is fairly slow, and the RAM is small. What is the point in using such a system for the task which among all image processing processes is the most ressource-hungry one?

Best regards,
 Rolf

**Comment by rbarbera** [comment]
Hi Rolf,

I don't pretend that you waste your time building the Raspberry wheel. That not was my idea when I started to play with it. I only need to know if the missing dependence was needed. Is not, so fine, I can continue with my exploration.

About the name, what setup.py proposes is `planetary_system_stacker-0.8.0-py3-none-linux_armv7l.whl`and I'm working with it right now.

And my motivations... why will I want to have PSS installed on a Raspberry? Well as I'm currently using it to control the telescope mount, guiding CCD/imaging CCD I want to have a way to quickly check the real quality of the videos I'm taking in the field. Is the same motivation that has drive me to build SiriL also on this platform. Yes, I know, perhaps it will be a waste of time (I expect that mainly, only my time).

Thanks for your insights and your kindly help!

Best regards, 
Rafa

**Comment by Rolf-Hempel** [comment]
Hi Rafa,

Thank you for telling me the name of the whl file. I uploaded a wheel file with that name to the test server. You can install PSS from there by typing
`pip3 install --index-url https://test.pypi.org/simple/ planetary-system-stacker==0.8.11`
Could you please uninstall PSS and reinstall it from the test server to confirm that this works?

Also, could you please tell me the name of the repository where you found the other dependencies for the ARM processor? I could include this info in the user guide for other users.

All the best,
 Rolf

**Comment by rbarbera** [comment]
I've been using the standard raspbian repo

```
sudo apt install -y python3-pyqt5 python3-qtpy python3-qt-binding
```

But I'm still having the problem with `mkl`. Could you remove it from the wheel for this platform?

```
astroberry@astroberry:~ $ pip3 install --index-url https://test.pypi.org/simple/ planetary-system-stacker==0.8.11

Looking in indexes: https://test.pypi.org/simple/, https://www.piwheels.org/simple
Collecting planetary-system-stacker==0.8.11
  Downloading https://test-files.pythonhosted.org/packages/64/2f/ca6621ecfc21439cfa3994f16c83fcc84971520159829ad058abd41c6b29/planetary_system_stacker-0.8.11-py3-none-linux_armv7l.whl (208kB)
    100% |████████████████████████████████| 215kB 992kB/s 
Collecting matplotlib (from planetary-system-stacker==0.8.11)
  Using cached https://www.piwheels.org/simple/matplotlib/matplotlib-3.3.2-cp37-cp37m-linux_armv7l.whl
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from planetary-system-stacker==0.8.11) (5.5.1)
Collecting scikit-image (from planetary-system-stacker==0.8.11)
  Using cached https://www.piwheels.org/simple/scikit-image/scikit_image-0.17.2-cp37-cp37m-linux_armv7l.whl
Requirement already satisfied: astropy in /usr/lib/python3/dist-packages (from planetary-system-stacker==0.8.11) (3.1.2)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from planetary-system-stacker==0.8.11) (1.1.0)
Collecting opencv-python (from planetary-system-stacker==0.8.11)
  Using cached https://www.piwheels.org/simple/opencv-python/opencv_python-4.4.0.44-cp37-cp37m-linux_armv7l.whl
Collecting mkl (from planetary-system-stacker==0.8.11)
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://test.pypi.org/simple/mkl/
```

**Comment by rbarbera** [comment]
Well, at the end, I think that this is a closed road. After handle to install all dependencies and running it from sources, I begun to receive run time errors on the dependencies. So please, don't waste more time with this proposal. And thank you very much for your interest and support.

<img width="1092" alt="Screenshot 2020-09-28 at 00 07 13" src="https://user-images.githubusercontent.com/338748/94377094-f8380680-011e-11eb-9a66-5fb12187f369.png">

**Comment by Rolf-Hempel** [comment]
Hi Rafa,

Too bad! I have no idea why the OpenCV library routine failed. Without a working Raspberry environment it is impossible for me to find out. Therefore, I agree that it would be very hard to get the problem fixed.

I'm sorry that you wasted so much time on installing PSS on your Raspberry Pi.

All the best,
 Rolf
