### ISSUE TITLE
PSS failing to build on OSX 10.15.7 Catalina

### ISSUE THREAD

**Issue by Lightwel** [Rolf-Hempel/PlanetarySystemStacker#32]
Good morning

I don't know if this is a Catalina-3-bit-only problem, or a SIP problem, or something else.  I am working from the PSS Installation Guide.

My guess from the architecture error messages is that this is (another) situation where I should have installed Mojave.  But I have not found anything on the web forums saying that PSS will not work with Catalina. Indeed the discussion on Cloudynights suggests it does basically work.

Below is my installation log

'''
richardhornby@Richards-MBP ~ % pip3 install planetary-system-stacker
Collecting planetary-system-stacker
  Downloading https://files.pythonhosted.org/packages/5c/7d/9d82c86af43a31af7dd86c9bcc313bd2dee2b6bf5f1a6a3be008d482ada6/planetary_system_stacker-0.8.14-py3-none-macosx_10_6_intel.whl (209kB)
     |████████████████████████████████| 215kB 5.5MB/s 
Collecting mkl (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/ac/1e/c713b011b90cd238023df1c0025130c40bc40870a46273d942e89114233c/mkl-2019.0-py2.py3-none-macosx_10_12_intel.macosx_10_12_x86_64.whl (193.8MB)
     |████████████████████████████████| 193.8MB 1.4MB/s 
Collecting psutil (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/33/e0/82d459af36bda999f82c7ea86c67610591cf5556168f48fd6509e5fa154d/psutil-5.7.3.tar.gz (465kB)
     |████████████████████████████████| 471kB 8.6MB/s 
Collecting PyQt5 (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/0f/28/fcaf2aeede42456538d1543aefa253d70282bf326f5f795c99233366b66f/PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_13_intel.whl (47.6MB)
     |████████████████████████████████| 47.6MB 8.4MB/s 
Collecting scikit-image (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/2e/db/17f9e6243c167f1ff544ef1eb4320a044c58abeecbe9f862acc29681af0f/scikit_image-0.17.2-cp38-cp38-macosx_10_13_x86_64.whl (12.2MB)
     |████████████████████████████████| 12.2MB 7.7MB/s 
Collecting scipy (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/50/92/f9eb8b164df26b8d91ed15d09647013d6eaf97c8e263bd20eff08e0bf997/scipy-1.5.4-cp38-cp38-macosx_10_9_x86_64.whl (29.0MB)
     |████████████████████████████████| 29.0MB 9.4MB/s 
Collecting astropy (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/e2/98/ec2278142d0fea9afa862ece8f4949a35cb5da88156b146a8e208226f0a4/astropy-4.2-cp38-cp38-macosx_10_9_x86_64.whl (6.5MB)
     |████████████████████████████████| 6.5MB 8.4MB/s 
Collecting opencv-python-headless (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/f2/91/db6df23fc730d85054dc05e9ff2ebe5b656b03c664922a4024191aad4034/opencv_python_headless-4.4.0.46-cp38-cp38-macosx_10_13_x86_64.whl (43.5MB)
     |████████████████████████████████| 43.5MB 8.2MB/s 
Collecting matplotlib (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/e8/7a/e3563e34443bb3f65fe0c301122124523b1543ae72b4c77442a548beeb5a/matplotlib-3.3.3-cp38-cp38-macosx_10_9_x86_64.whl (8.5MB)
     |████████████████████████████████| 8.5MB 7.8MB/s 
Collecting intel-openmp (from mkl->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/df/51/1138f9df9fa1659c035927297d275a57404f174a1405febe4a5084e77320/intel_openmp-2019.0-py2.py3-none-macosx_10_12_intel.macosx_10_12_x86_64.whl (1.1MB)
     |████████████████████████████████| 1.1MB 9.2MB/s 
Collecting PyQt5-sip<13,>=12.8 (from PyQt5->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/51/92/af676068a945d047fab697adddc82ede4264c98ed82447533ce8ef02622f/PyQt5_sip-12.8.1-cp38-cp38-macosx_10_9_x86_64.whl (63kB)
     |████████████████████████████████| 71kB 8.9MB/s 
Collecting tifffile>=2019.7.26 (from scikit-image->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/e7/53/201a945e74d8d7a3a6025eaef8a73950b732906bb96da642e5f1d0ee3341/tifffile-2020.11.18-py3-none-any.whl (153kB)
     |████████████████████████████████| 163kB 8.8MB/s 
Collecting networkx>=2.0 (from scikit-image->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/9b/cd/dc52755d30ba41c60243235460961fc28022e5b6731f16c268667625baea/networkx-2.5-py3-none-any.whl (1.6MB)
     |████████████████████████████████| 1.6MB 8.2MB/s 
Collecting numpy>=1.15.1 (from scikit-image->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/0b/bc/a5eecf00251948d1c31434c6164368767e5c860984a99ca571ae505c37ea/numpy-1.19.4-cp38-cp38-macosx_10_9_x86_64.whl (15.3MB)
     |████████████████████████████████| 15.3MB 7.9MB/s 
Collecting PyWavelets>=1.1.1 (from scikit-image->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/77/fa/cd182609e276d8ea7315a084cf2acbd0f39751e56562555bd8e4a0131498/PyWavelets-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (4.3MB)
     |████████████████████████████████| 4.4MB 8.9MB/s 
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0 (from scikit-image->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/b2/99/219de493bf9bda6e36e52bded5771a42ed68d5731c715518a2d771b9b2a1/Pillow-8.0.1-cp38-cp38-macosx_10_10_x86_64.whl (2.2MB)
     |████████████████████████████████| 2.2MB 9.4MB/s 
Collecting imageio>=2.3.0 (from scikit-image->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/6e/57/5d899fae74c1752f52869b613a8210a2480e1a69688e65df6cb26117d45d/imageio-2.9.0-py3-none-any.whl (3.3MB)
     |████████████████████████████████| 3.3MB 8.8MB/s 
Collecting pyerfa (from astropy->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/49/21/f63950b236bab06b5ae6b6a84c188526be563014a96a4e0331dd3c5864c3/pyerfa-1.7.1.1-cp38-cp38-macosx_10_9_x86_64.whl (305kB)
     |████████████████████████████████| 307kB 9.2MB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/0c/89/cdd752da48b66f31a0732902cd9800e6d232ce65f6cc4e83f9d9d2bd99aa/kiwisolver-1.3.1-cp38-cp38-macosx_10_9_x86_64.whl (61kB)
     |████████████████████████████████| 71kB 9.4MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
     |████████████████████████████████| 71kB 8.6MB/s 
Collecting cycler>=0.10 (from matplotlib->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
     |████████████████████████████████| 235kB 8.4MB/s 
Collecting decorator>=4.3.0 (from networkx>=2.0->scikit-image->planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Requirement already satisfied: six in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from cycler>=0.10->matplotlib->planetary-system-stacker) (1.15.0)
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b2/lnrj5cnd6yjggq8y9fvtgf4h0000gn/T/pip-install-62s5lnou/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/b2/lnrj5cnd6yjggq8y9fvtgf4h0000gn/T/pip-install-62s5lnou/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/b2/lnrj5cnd6yjggq8y9fvtgf4h0000gn/T/pip-wheel-5u96y24v --python-tag cp38
       cwd: /private/var/folders/b2/lnrj5cnd6yjggq8y9fvtgf4h0000gn/T/pip-install-62s5lnou/psutil/
  Complete output (141 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14.6-x86_64-3.8
  creating build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_pswindows.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_common.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/__init__.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_psosx.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_psbsd.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_psaix.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_pslinux.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_compat.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_psposix.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  copying psutil/_pssunos.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil
  creating build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/runner.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_memleaks.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  copying psutil/tests/test_testutils.py -> build/lib.macosx-10.14.6-x86_64-3.8/psutil/tests
  running build_ext
  building 'psutil._psutil_osx' extension
  creating build/temp.macosx-10.14.6-x86_64-3.8
  creating build/temp.macosx-10.14.6-x86_64-3.8/psutil
  creating build/temp.macosx-10.14.6-x86_64-3.8/psutil/arch
  creating build/temp.macosx-10.14.6-x86_64-3.8/psutil/arch/osx
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_OSX=1 -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c psutil/_psutil_common.c -o build/temp.macosx-10.14.6-x86_64-3.8/psutil/_psutil_common.o
  In file included from psutil/_psutil_common.c:9:
  In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
  In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:63:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
  #error Unsupported architecture
   ^
  In file included from psutil/_psutil_common.c:9:
  In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
  In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:64:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported
  #error architecture not supported
   ^
  In file included from psutil/_psutil_common.c:9:
  In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
  #error architecture not supported
   ^
  In file included from psutil/_psutil_common.c:9:
  In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
  typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
  typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
          ^
  note: '__int128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
  typedef __int32_t       __darwin_dev_t;         /* dev_t */
          ^
  note: '__int128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
  typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
          ^
  note: '__uint128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
  typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
          ^
  note: '__uint128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
  typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
  typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
  typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
          ^
  note: '__uint128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
  typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
  typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
          ^
  note: '__int128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
  typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
          ^
  note: '__uint128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
  typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
          ^
  note: '__int128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
  typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
          ^
  note: '__uint128_t' declared here
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
  typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
          ^
  note: '__uint128_t' declared here
  In file included from psutil/_psutil_common.c:9:
  In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
  typedef __uint32_t      __darwin_wctype_t;
          ^
  note: '__uint128_t' declared here
  In file included from psutil/_psutil_common.c:9:
  In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
  #error architecture not supported
   ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: intel-openmp, mkl, psutil, PyQt5-sip, PyQt5, numpy, tifffile, scipy, decorator, networkx, PyWavelets, pillow, kiwisolver, pyparsing, cycler, python-dateutil, matplotlib, imageio, scikit-image, pyerfa, astropy, opencv-python-headless, planetary-system-stacker
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
Consider using the `--user` option or check the permissions.

'''

Any help gratefully recieved.

Many thanks

**Comment by Rolf-Hempel** [comment]
Hi Lightwel,

As you might have seen in the discussion on Cloudy Nights, I cannot comment on any MacOS installation issues because I have never used a Mac computer. I suggest that you post your problem on Cloudy Nights where several experienced Mac users will read your report. In similar cases they could help to resolve the problem.

I'm sorry that I cannot provide any help myself.

All the best,
 Rolf

**Comment by Lightwel** [comment]
Thanks for taking the trouble to reply.

Will do.

Best

R

**Comment by ghilios** [comment]
@Lightwel see this thread: https://github.com/ycm-core/YouCompleteMe/issues/3770

This looks to be an issue with the python that ships with brew on Catalina. I suggest downloading the official python3 distribution.

**Comment by Lightwel** [comment]
Hi George. Thanks for your reply, which coincidentally arrived as I was going through the thread on CN https://www.cloudynights.com/topic/645890-new-stacking-software-project-planetarysystemstacker/ <https://www.cloudynights.com/topic/645890-new-stacking-software-project-planetarysystemstacker/>

Tks for the steer.  I also downloaded the Xcode CLI tools from the App Store but having read the thread you recommended will get 3.9 from the official repo.

Currently my terminal reads:

richardhornby@Richards-MBP % which python
/usr/bin/python
richardhornby@Richards-MBP % python --version
Python 2.7.16
richardhornby@Richards-MBP % python3 --version  
Python 3.8.2
richardhornby@Richards-MBP % which python3
/usr/bin/python3

Is it just python 3.9 I need or do I need any of the libraries mentioned on in post #53 on the CN thread eg ? And do I need numpy (post #689)?

If so, where would I get them and how / where install? 

And should I uninstall 2/9?

(I am used to Manjaro/Arch Linux and getting libraries automatically installed via pacman/pamac, but am trying to keep all my progs in one OS for the moment.) 

Best

R
