### ISSUE TITLE
Errors on launching PSS from console

### ISSUE THREAD

**Issue by sharkking76** [Rolf-Hempel/PlanetarySystemStacker#33]
Hello,

installed python (3.6.8) and PSS according to the documentation. Download and Install of all depencies was running fine.
However when trying to run PSS get the following Erros.

`C:\Users\andy\AppData\Local\Programs\Python\Python36>PlanetarySystemStacker
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "c:\users\andy\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andy\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\andy\AppData\Local\Programs\Python\Python36\Scripts\PlanetarySystemStacker.exe\__main__.py", line 5, in <module>
  File "c:\users\andy\appdata\local\programs\python\python36\lib\site-packages\planetary_system_stacker\planetary_system_stacker.py", line 37, in <module>
    import cv2
  File "c:\users\andy\appdata\local\programs\python\python36\lib\site-packages\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

C:\Users\andy\AppData\Local\Programs\Python\Python36>python.exe
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z

C:\Users\andy\AppData\Local\Programs\Python\Python36>`

Is there anything i could have done wrong ?

`C:\Users\andy\AppData\Local\Programs\Python\Python36>pip3 install planetary-system-stacker
Requirement already satisfied: planetary-system-stacker in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (0.8.14)
Requirement already satisfied: opencv-python in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (4.4.0.46)
Requirement already satisfied: PyQt5 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (5.15.2)
Requirement already satisfied: matplotlib in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (3.3.3)
Requirement already satisfied: scikit-image in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (0.17.2)
Requirement already satisfied: scipy in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (1.5.4)
Requirement already satisfied: psutil in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (5.7.3)
Requirement already satisfied: astropy in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (4.1)
Requirement already satisfied: mkl in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from planetary-system-stacker) (2021.1.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from opencv-python->planetary-system-stacker) (1.19.4)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from PyQt5->planetary-system-stacker) (12.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->planetary-system-stacker) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->planetary-system-stacker) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->planetary-system-stacker) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->planetary-system-stacker) (8.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->planetary-system-stacker) (1.3.1)
Requirement already satisfied: networkx>=2.0 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from scikit-image->planetary-system-stacker) (2.5)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from scikit-image->planetary-system-stacker) (2020.9.3)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from scikit-image->planetary-system-stacker) (1.1.1)
Requirement already satisfied: imageio>=2.3.0 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from scikit-image->planetary-system-stacker) (2.9.0)
Requirement already satisfied: tbb==2021.* in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from mkl->planetary-system-stacker) (2021.1.1)
Requirement already satisfied: intel-openmp==2021.* in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from mkl->planetary-system-stacker) (2021.1.1)
Requirement already satisfied: six in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from cycler>=0.10->matplotlib->planetary-system-stacker) (1.15.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\andy\appdata\local\programs\python\python36\lib\site-packages (from networkx>=2.0->scikit-image->planetary-system-stacker) (4.4.2)`

Thanks and Regards

Andreas

**Comment by Rolf-Hempel** [comment]
Hi Andreas,

This sounds like a well-known library inconsistency problem. Could you please try the following:
`pip3 uninstall numpy`
`pip3 install numpy==1.18.4`
The problem is that pip found an older numpy version on your system and was happy with it.

Does this solve your problem?

All the best,
 Rolf

**Comment by sharkking76** [comment]
Perfect, Thanks a lot.

**Comment by sharkking76** [comment]
Solved with the above Solution
