### ISSUE TITLE
problem installing PSS on MacBook Pro

### ISSUE THREAD

**Issue by jan-verbist** [Rolf-Hempel/PlanetarySystemStacker#34]
I tried to install PSS following the instruction of the PSS User Guide.
I installed python 3.9 and then launched 'pip3 install planetary-system-stacker"
This is the result of the command :
MacBook-Pro:~ janverbist$ pip3 install planetary-system-stacker
Collecting planetary-system-stacker
  Using cached planetary_system_stacker-0.8.14-py3-none-macosx_10_6_intel.whl (209 kB)
Collecting astropy
  Using cached astropy-4.2-cp39-cp39-macosx_10_9_x86_64.whl (6.5 MB)
Collecting matplotlib
  Using cached matplotlib-3.3.3-cp39-cp39-macosx_10_9_x86_64.whl (8.5 MB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp39-cp39-macosx_10_9_x86_64.whl (61 kB)
Collecting mkl
  Using cached mkl-2021.1.1-py2.py3-none-macosx_10_15_x86_64.whl (265.3 MB)
Collecting intel-openmp==2021.*
  Using cached intel_openmp-2021.1.1-py2.py3-none-macosx_10_15_x86_64.whl (1.2 MB)
Collecting numpy>=1.17
  Using cached numpy-1.19.4-cp39-cp39-macosx_10_9_x86_64.whl (15.4 MB)
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.4.0.46-cp39-cp39-macosx_10_13_x86_64.whl (43.5 MB)
Collecting pillow>=6.2.0
  Using cached Pillow-8.0.1-cp39-cp39-macosx_10_10_x86_64.whl (2.2 MB)
Collecting psutil
  Using cached psutil-5.7.3.tar.gz (465 kB)
Collecting pyerfa
  Using cached pyerfa-1.7.1.1-cp39-cp39-macosx_10_9_x86_64.whl (301 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_13_intel.whl (47.6 MB)
Collecting PyQt5-sip<13,>=12.8
  Using cached PyQt5_sip-12.8.1-cp39-cp39-macosx_10_9_x86_64.whl (63 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting scikit-image
  Using cached scikit-image-0.17.2.tar.gz (29.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rf/1jmwmp516gdd9m4md27d41gm0000gn/T/pip-install-dnb12_8h/scikit-image_0afcc36f093f4a7091aace200cef4070/setup.py'"'"'; __file__='"'"'/private/var/folders/rf/1jmwmp516gdd9m4md27d41gm0000gn/T/pip-install-dnb12_8h/scikit-image_0afcc36f093f4a7091aace200cef4070/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rf/1jmwmp516gdd9m4md27d41gm0000gn/T/pip-pip-egg-info-_qe31wh3
         cwd: /private/var/folders/rf/1jmwmp516gdd9m4md27d41gm0000gn/T/pip-install-dnb12_8h/scikit-image_0afcc36f093f4a7091aace200cef4070/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rf/1jmwmp516gdd9m4md27d41gm0000gn/T/pip-install-dnb12_8h/scikit-image_0afcc36f093f4a7091aace200cef4070/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/private/var/folders/rf/1jmwmp516gdd9m4md27d41gm0000gn/T/pip-install-dnb12_8h/scikit-image_0afcc36f093f4a7091aace200cef4070/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

How can I resolve this error ?

Thanks,
Jan

**Comment by Rolf-Hempel** [comment]
Hi,

I cannot comment on this issue because I have never touched a Mac computer in my whole life. 

@ghilios Could you please have a look at this issue? Thanks!

All the best,
 Rolf

**Comment by jan-verbist** [comment]
Hi Rolf,

After some investigation I found that the scikit-image package is causing the problem. I upgraded to Python 3.9 but when I look at the scikit-image site https://pypi.org/project/scikit-image/#description <https://pypi.org/project/scikit-image/#description>
There is not yet a version of scikit-image available for python 3.9. Maybe that is the reason I can’t install this package. 

Best regards,

Jan

**Comment by ghilios** [comment]
Jan, perhaps you can try an earlier version of python, such as 3.6? None of the contributors has a mac device, but if you're willing to install TeamViewer perhaps we can arrange a time for me to connect and find a way to get it to work.

**Comment by jan-verbist** [comment]
Hi, I installed the 3.8 version of python and this worked without a problem. Generally I followed the instructions as mentioned in the PSS manual but I also used a virtual environment to install the package.
The challenge now is to use the PSS properly and get nice results. 
Thanks for your mail.

Best regards,

Jan Verbist

**Comment by ghilios** [comment]
Great! Perhaps we should make a note regarding which Python versions are supported (clearly not 3.9 yet :) )

**Comment by Rolf-Hempel** [comment]
We could add the requirement in the PyPI wheel for Mac that Python be < 3.9. What do you think?

**Comment by ghilios** [comment]
This sounds right to me!

**Comment by Rolf-Hempel** [comment]
I just changed the setup file for MacOS. With the next minor release on PyPI the new requirement "Python < 3.9" will be effective.
