### ISSUE TITLE
Problem with PyQt5 dependency in PIP

### ISSUE THREAD

**Issue by javiersanp** [Rolf-Hempel/PlanetarySystemStacker#35]
Not a issue with the program but I report in case it's worth to mention in the requeriments that a recent version of pip is needed.

I done two install in two Ubuntu box2 with pip 18.1  and get this problem in both:

```
Collecting PyQt5 (from planetary-system-stacker)
  Downloading https://files.pythonhosted.org/packages/28/6c/640e3f5c734c296a7193079a86842a789edb7988dca39eab44579088a1d1/PyQt5-5.15.2.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 6.5MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jsanchez/.pyenv/versions/3.7.2/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ug8t3g1y/PyQt5/setup.py'
```

Solved upgrading pip to 20.3.3

    pip install --upgrade pip

**Comment by Rolf-Hempel** [comment]
Hi,

Thank you very much for your report! That is very strange, because on my Windows 10 pip3 version 18.1 works just fine with PSS.

I'm glad you could solved the problem on your Ubuntu by upgrading pip.

All the best,
 Rolf
