### ISSUE TITLE
Issue with Linux Ubuntu 20.04.3

### ISSUE THREAD

**Issue by Bobby512** [Rolf-Hempel/PlanetarySystemStacker#47]
Hello,

I discovered recently this tools. I install it on my laptop with Ubuntu 20.04.3. The first tries are very good. Next I wanted install it on my desktop with Ubuntu 20.04.3 too. But I meet issues.

robert@robert-M11AD:~/.local/bin$ PlanetarySystemStacker
QObject::moveToThread: Current thread (0x277aff0) is not the object's thread (0x3447210).
Cannot move to target thread (0x277aff0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/robert/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Abandon
robert@robert-M11AD:~/.local/bin$

I understand the issue is about QT but I can't resolve it.

**Comment by Rolf-Hempel** [comment]
Hi,

Sorry for my late answer. We have seen this problem before. In [this Cloudy Nights thread](https://www.cloudynights.com/topic/645890-new-stacking-software-project-planetarysystemstacker/?p=10829594) a solution is given. Does this work in your case?

**Comment by Bobby512** [comment]
Hello,
I install opencv-python-headless and planetary-system-stacker_0.8.31-2_all.deb. When I launch PSS I obtain:

robert@robert-M11AD:~$ PlanetarySystemStacker
/home/robert/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/robert/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/robert/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 1.13.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/home/robert/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/usr/bin/PlanetarySystemStacker", line 33, in <module>
    sys.exit(load_entry_point('planetary-system-stacker==0.8.31', 'console_scripts', 'PlanetarySystemStacker')())
  File "/usr/lib/python3/dist-packages/planetary_system_stacker/planetary_system_stacker.py", line 1459, in main
    myapp = PlanetarySystemStacker()
  File "/usr/lib/python3/dist-packages/planetary_system_stacker/planetary_system_stacker.py", line 322, in __init__
    self.display_widget(DisplayQuickstart(self, self.configuration))
  File "/usr/lib/python3/dist-packages/planetary_system_stacker/display_quickstart.py", line 46, in __init__
    self.label.setTextFormat(Qt.MarkdownText)
AttributeError: type object 'Qt' has no attribute 'MarkdownText'
robert@robert-M11AD:~$

**Comment by Rolf-Hempel** [comment]
Hello,

Where does "planetary-system-stacker_0.8.31-2_all.deb" come from? Did you use that package on your laptop as well, where everything worked fine? You are not installing from the PyPI server, do you?

The error message you listed has to do with the Quickstart Guide displayed when PSS starts. There were discussions on that on Cloudy Nights as well, for example in [this posting](https://www.cloudynights.com/topic/645890-new-stacking-software-project-planetarysystemstacker/?p=10818804). Why don't you post your problem in [this Cloudy Nights thread](https://www.cloudynights.com/topic/753290-planetarysystemstacker-installation-issues/page-2). There are many users who have have solved installation issues on various HW platforms.

**Comment by Rolf-Hempel** [comment]
Hi alexantao,

Thanks for your positive comment! As to the .desktop file, this depends on the desktop environment you use (KDE or Gnome). I always have to google how one can create such a starter file, but I don't think it is that hard to do. 

All the best,
 Rolf

**Comment by Rolf-Hempel** [comment]
I think we can close this issue now, right?

**Comment by Bobby512** [comment]
Yes, sûre.

⁣Télécharger BlueMail pour Android ​

Le 13 janv. 2023 à 09:00, à 09:00, Rolf Hempel ***@***.***> a écrit:
