### ISSUE TITLE
Cannot run PSS from the CLI without display on ubuntu (headless)

### ISSUE THREAD

**Issue by timing** [Rolf-Hempel/PlanetarySystemStacker#61]
I want to run PSS "in the cloud". I booted a fresh VPS with Ubuntu 22.04 and did the following:

```
apt update
apt install python3-pip
pip3 install planetary-system-stacker
```

Then I run the following:

```
PlanetarySystemStacker 01022023205211-trimmed.mov -p -b 4 -s 25 -a 52 -w 20 –n --drizzle 1.5x
```

(this is from the example in the documentation PDF)

But it errors on QT stuff. I'd assume running the tool headless does not need QT right?

```
Traceback (most recent call last):
  File "/usr/local/bin/PlanetarySystemStacker", line 5, in <module>
    from planetary_system_stacker.planetary_system_stacker import main
  File "/usr/local/lib/python3.10/dist-packages/planetary_system_stacker/planetary_system_stacker.py", line 42, in <module>
    from PyQt5 import QtWidgets, QtCore, QtGui
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by Rolf-Hempel** [comment]
Hi Tijmen,

The CLI does not use any GUI for user interaction, but it still uses the QT signals (from QtCore). Is PyQt5 not installed on your system?

All the best,
 Rolf

**Comment by timing** [comment]
The system I use does not have a display (it's on a VPS), so it cannot connect to the display, hence the error. I fix this by running Xfvb, which sets up a virtual display. However this takes quite some memory, and shows that PSS is not really a "true CLI tool", which is maybe not one of your goals, but I would like that :-).

**Comment by Rolf-Hempel** [comment]
You are right: PSS primarily is a GUI tool. As you can see in the code, the CLI version shares most of the code with the GUI version. I only wanted to give users the opportunity to integrate PSS in more complex workflows for automation. I guess that creating a PSS version with all the QT stuff removed would take some time.  :-(
