### ISSUE TITLE
Problem with NumPy on MacOS Monterey with Python3.11: NumPy 1.22.4 may not yet support Python 3.11

### ISSUE THREAD

**Issue by crizzzly** [Rolf-Hempel/PlanetarySystemStacker#71]
Collecting numpy<1.23.0 (from planetary-system-stacker)
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      <string>:66: RuntimeWarning: `NumPy 1.22.4 may not yet support Python 3.11`.
      Running from numpy source directory.
      running egg_info
      running build_src
      INFO: build_src
      creating numpy.egg-info
      writing numpy.egg-info/PKG-INFO
      writing dependency_links to numpy.egg-info/dependency_links.txt
      writing entry points to numpy.egg-info/entry_points.txt
      writing top-level names to numpy.egg-info/top_level.txt
      writing manifest file 'numpy.egg-info/SOURCES.txt'

**Comment by Rolf-Hempel** [comment]
This seems to me to be a numpy issue rather than a PSS one (see the RuntimeWarning). I never tried to install PSS on Python 3.11.
