### ISSUE TITLE
OpenCV: Cannot read SER on ubuntu 22.04

### ISSUE THREAD

**Issue by petmos** [Rolf-Hempel/PlanetarySystemStacker#79]
I installed version 0.9.8 with `pip3 install planetary-system-stacker`
When I try to read a ser file it fails after hitting the "Start/Cont." button.
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
***************************************************************************
18-23-08.4 Start processing /data/Astro/indi_record_2023-11-19@16-30-22.ser
           Software version used: PlanetarySystemStacker 0.9.8
***************************************************************************
18-23-11.3 Error in opening/reading frames: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/demosaicing.cpp:1740: error: (-215:Assertion failed) depth == CV_8U in function 'demosaicing'
, continuing with next job

```
If I has to provide more information please tell me.
And thank you for your grat work.

**Comment by petmos** [comment]
Used Python version:
Python 3.10.12

**Comment by petmos** [comment]
Sorry, accidently closed the issue.

**Comment by petmos** [comment]
I tried the same SER file on a Windows installation and it worked there.

**Comment by Chris2000SP** [comment]
I am no Developer but experienced Linux user. Did you try to install "python3-opencv"?

**Comment by petmos** [comment]
The problem was in front of the monitor.
I recorded with the wrong Bayer Matrix.
