### ISSUE TITLE
Load .pss configuration file from CLI

### ISSUE THREAD

**Issue by timing** [Rolf-Hempel/PlanetarySystemStacker#81]
As far as I know it's not possible to run PSS from CLI including passing a configuration file saved in the GUI of the application. But this would be great for automation purposes, including post processing.

I could also try to fix it myself and send a pull request, but I would need some pointers :-)

**Comment by timing** [comment]
Hi, I made it work here: 

https://github.com/timing/PlanetarySystemStacker/compare/1155a16d39b46351ebeb2c444514777e0b816e2b...da5caf093e4bf955250533dd3f46d23db610b893

My fork also puts all the files in a `src` dir instead of `planetary_system_stacker`, this works better with the `pyproject.toml` file I created. If you would merge this, it also means you have to accept the change in directory structure. And I don't know if the pyproject.toml works well for windows and linux.

**Comment by Rolf-Hempel** [comment]
Hi Tijmen,

Thank you for sharing your modified PSS. I had a look at the changes you made, and I agrre that the requested change can be implemented this way.

I hesitate, however, to include the change in the PSS main branch. I added the CLI option for applications where PSS is invoked from some other code automatically. In this scenario the CLI string is created by some software, and not by hand. In this scenario to me it looks like the easiest way of passing arguments to PSS to just paste them into the CLI string.

Passing them via a configuration file would make most sense to me if this file was saved at a previous PSS session by a human. In this scenario you have a kind of hybrid processing, first by invoking the GUI and setting the parameters, and then by running the other software which calls PSS automatically. I'm not convinced that enough users would ask for this feature to justify the change.

I appreciate the effort you put into implementing the feature, and I hope that it will not be too awkward for you to work with your locally modified PSS.

All the best,
 Rolf
